-- ALTER TABLE EMPLOYEE (ADD) --

ALTER TABLE EMPLOYEE_CSB30 ADD CITY VARCHAR2(50);

-- ALTER TABLE EMPLOYEE (MODIFY) --

ALTER TABLE EMPLOYEE_CSB30 MODIFY SALARY NUMBER (10,3);

-- ALTER TABLE (ADD CONSTRAINT) --

ALTER TABLE EMPLOYEE_CSB30 ADD CONSTRAINT SAL CHECK (SALARY > 0);

-- ALTER TABLE EMPLOYEE (DROP CONSTRAINT) --

ALTER TABLE EMPLOYEE_CSB30 DROP CONSTRAINT SAL;

-- INSERT VALUES INTO DEPARTMENT TABLE --

INSERT INTO DEPARTMENT_CSB30 VALUES (1,'COMPUTER SCIENCE','CSE');
INSERT INTO DEPARTMENT_CSB30 VALUES (2,'INFORMATION TECHNOLOGY','IT');
INSERT INTO DEPARTMENT_CSB30 VALUES (3,'ELECTRICAL & ELECTRONICS','EEE');
INSERT INTO DEPARTMENT_CSB30 VALUES (4,'ELECTRONICS & COMMUNICATION','ECE');
INSERT INTO DEPARTMENT_CSB30 VALUES (5,'MECHANICAL','ME');

-- INSERT INTO PROJECT TABLE --

INSERT INTO PROJECT_CSB30 VALUES ('P1','ML PROJECT',1);
INSERT INTO PROJECT_CSB30 VALUES ('P2','APP DEV PROJECT',2);
INSERT INTO PROJECT_CSB30 VALUES ('P3','SMART ENERGY PROJECT',3);
INSERT INTO PROJECT_CSB30 VALUES ('P4','AIOT PROJECT',4);
INSERT INTO PROJECT_CSB30 VALUES ('P5','AUTO MATERIAL HANDLING PROJECT',5);

-- INSERT INTO EMPLOYEE TABLE --

INSERT INTO EMPLOYEE_CSB30 VALUES ('E1','ARUN','MANAGER', 'M', 30, 550000.25, TO_DATE('2015-06-01','YYYY-MM-DD'), 'P1', 'KOCHI');
INSERT INTO EMPLOYEE_CSB30 VALUES ('E2','MAYA','ACCOUNTANT', 'F', 25, 50000.00, TO_DATE('2017-07-01','YYYY-MM-DD'), 'P2', 'PALAKKAD');
INSERT INTO EMPLOYEE_CSB30 VALUES ('E3', 'SHON', 'SR ENGINEER', 'M', 20, 200000.00, TO_DATE('2018-08-15','YYYY-MM-DD'), 'P3', 'KOLLAM');
INSERT INTO EMPLOYEE_CSB30 VALUES ('E4', 'ASIF', 'HARDWARE TECHNICIAN', 'M', 20, 150000.00, TO_DATE('2019-05-15','YYYY-MM-DD'), 'P4', 'KOLLAM');
INSERT INTO EMPLOYEE_CSB30 VALUES ('E5', 'SREE LEKSHMI', 'PROD ENGINEER', 'F', 22, 50000.00, TO_DATE('2020-06-15','YYYY-MM-DD'), 'P5', 'THRISSUR');

-- VIEWING DEPARTMENT TABLE --

SELECT * FROM DEPARTMENT_CSB30;

-- VIEWING PROJECT TABLE --

SELECT * FROM PROJECT_CSB30;

-- VIEWING EMPLOYEE TABLE --

SELECT * FROM EMPLOYEE_CSB30;


