-- CREATE DEPARTMENT TABLE --

CREATE TABLE DEPARTMENT (
    DEPTNO    NUMBER PRIMARY KEY,
    DEPTNAME  VARCHAR2(50),
    LOCATION  VARCHAR2(20) CHECK (LOCATION IN ('CSE', 'IT', 'EEE', 'ECE', 'ME'))
);

-- RENAME DEPARTMENT --

RENAME DEPARTMENT TO DEPARTMENT_CSB30;

-- CREATE TABLE PROJECT --

CREATE TABLE PROJECT (
    PNO VARCHAR2(20) PRIMARY KEY CHECK (PNO LIKE 'P%'),
    PNAME VARCHAR2(50),
    DEPTNO NUMBER,
    FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENT_CSB30(DEPTNO) 
); 

--RENAME PROJECT --

RENAME PROJECT TO PROJECT_CSB30;

-- CREATE TABLE EMPLOYEE --

CREATE TABLE EMPLOYEE_CSB30 (
    ENO VARCHAR2(20) PRIMARY KEY CHECK(ENO LIKE 'E%'),
    ENAME VARCHAR2(50),
    DESIGNATION VARCHAR2(50),
    SEX CHAR(1) CHECK (SEX IN ('M','F')),
    AGE NUMBER CHECK (AGE > 0),
    SALARY NUMBER (10,2),
    DATEOFJOIN DATE ,
    PNO VARCHAR2(20),
    FOREIGN KEY (PNO) REFERENCES PROJECT_CSB30 (PNO)
 );
